baseURL = "https://rationalgames.github.io/prisonlife-diary/"
title = "Prison Life Development Diary"
publishDir = "public"

theme = "smol"

[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "posts/"
        weight = 1

#  [[menu.main]]
#        identifier = "categories"
#        name = "Categories"
#        url = "categories/"
#        weight = 2

  [[menu.footer]]
        name = "Github"
        url = "https://github.com/rationalgames/prisonlife-diary"
        weight = 1

